In [53]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import datasets

In [54]:
# 보스턴 집값 데이터 (인종 차별적인 요소로 scikit-learn에서 제거, url 로드)
data_url = "http://lib.stat.cmu.edu/datasets/boston"

# 데이터 로드 (원시 문자열을 사용하여 '\s+'가 정규 표현식으로 인식되도록 함)
raw_df = pd.read_csv(data_url, sep=r"\s+", skiprows=22, header=None)

# 데이터와 타겟을 분리
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

X_boston = pd.DataFrame(data)
y_boston = pd.DataFrame(target) 
df_boston = pd.concat([X_boston, y_boston], axis=1)

print(len(df_boston))
print(df_boston.head())

506
        0     1     2    3      4      5     6       7    8      9     10  \
0  0.00632  18.0  2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3   
1  0.02731   0.0  7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8   
2  0.02729   0.0  7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8   
3  0.03237   0.0  2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0  18.7   
4  0.06905   0.0  2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0  18.7   

       11    12    0   
0  396.90  4.98  24.0  
1  396.90  9.14  21.6  
2  392.83  4.03  34.7  
3  394.63  2.94  33.4  
4  396.90  5.33  36.2  


In [55]:
feature_boston = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT']

col_boston=np.append(feature_boston, ['target'])
df_boston.columns = col_boston
df_boston.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [56]:
# 아이리스 꽃 분류하기
raw_iris = datasets.load_iris()
X_iris = pd.DataFrame(raw_iris.data)
y_iris = pd.DataFrame(raw_iris.target)
df_iris = pd.concat([X_iris, y_iris], axis=1)

feature_iris = raw_iris.feature_names
print(feature_iris)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [57]:
col_iris=np.append(feature_iris, ['target'])
df_iris.columns = col_iris
df_iris.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [58]:
# 와인 구분하기 
raw_wine = datasets.load_wine()
X_wine = pd.DataFrame(raw_wine.data)
y_wine = pd.DataFrame(raw_wine.target)
df_wine = pd.concat([X_wine, y_wine], axis=1)

feature_wine = raw_wine.feature_names
print(feature_wine)

['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']


In [59]:
col_wine=np.append(feature_wine, ['target'])
df_wine.columns = col_wine
df_wine.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  target  
0                          3.92   1065.0       0  
1                          3.40   1050.0       0  
2                          3.17   1185.0       0  
3                          3.45   1480.0       0  
4                          2.93    735.0       0

In [60]:
# 당뇨병 예측하기
raw_diab = datasets.load_diabetes()
X_diab = pd.DataFrame(raw_diab.data)
y_diab = pd.DataFrame(raw_diab.target)
df_diab = pd.concat([X_diab, y_diab], axis=1)

feature_diab = raw_diab.feature_names
print(feature_diab)

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']


In [61]:
col_diab=np.append(feature_diab, ['target'])
df_diab.columns = col_diab
df_diab.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  target  
0 -0.002592  0.019907 -0.017646   151.0  
1 -0.039493 -0.068332 -0.092204    75.0  
2 -0.002592  0.002861 -0.025930   141.0  
3  0.034309  0.022688 -0.009362   206.0  
4 -0.002592 -0.031988 -0.046641   135.0

In [62]:
# 유방암 예측하기
raw_bc = datasets.load_breast_cancer()
X_bc = pd.DataFrame(raw_bc.data)
y_bc = pd.DataFrame(raw_bc.target)
df_bc = pd.concat([X_bc, y_bc], axis=1)

feature_bc = raw_bc.feature_names
print(feature_bc)

['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']


In [63]:
col_bc=np.append(feature_bc, ['target'])
df_bc.columns = col_bc
df_bc.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

### 결측치 처리하기

**결측치란?**
데이터 셋의 일부에 데이터가 존재하지 않는 경우 

In [81]:
import numpy as np
import pandas as pd

# 결측치 포함 예시 데이터 프레임 생성
df = pd.DataFrame([
    [42, 'male', 12, 'reading', 'class2'],
    [35, 'unknown', 3, 'cooking', 'class1'],
    [1000, 'female', 7, 'cycling', 'class3'],
    [1000, 'unknown', 21, 'unknown', 'unknown']
])
df.columns=['age',
            'gender',
            'month_birth',
            'hobby', 'target']

df

age   gender  month_birth    hobby   target
0    42     male           12  reading   class2
1    35  unknown            3  cooking   class1
2  1000   female            7  cycling   class3
3  1000  unknown           21  unknown  unknown

In [82]:
# 유니크 값(부적절한 값) 확인
df['age'].unique()

array([  42,   35, 1000], dtype=int64)

In [83]:
print(df['gender'].unique())
print(df['month_birth'].unique())
print(df['hobby'].unique())
print(df['target'].unique())

['male' 'unknown' 'female']
[12  3  7 21]
['reading' 'cooking' 'cycling' 'unknown']
['class2' 'class1' 'class3' 'unknown']


In [101]:
# 부적절한 값을 결측치(nan)값으로 변환
df.loc[df['age']>150, ['age']] = np.nan
df.loc[df['gender']=='unknown', ['gender']] = np.nan
df.loc[df['month_birth']>12, ['month_birth']] = np.nan
df.loc[df['hobby']=='unknown', ['hobby']] = np.nan
df.loc[df['target']=='unknown', ['target']] = np.nan

df

age  gender  month_birth    hobby  target
0  42.0    male         12.0  reading  class2
1  35.0     NaN          3.0  cooking  class1
2   NaN  female          7.0  cycling  class3
3   NaN     NaN          NaN      NaN     NaN

In [102]:
# 각 열의 결측치 개수 확인
df.isnull().sum()

age            2
gender         2
month_birth    1
hobby          1
target         1
dtype: int64

In [103]:
# 결측치를 포함한 행 삭제
df2 = df.dropna(axis=0)
df2

age gender  month_birth    hobby  target
0  42.0   male         12.0  reading  class2

In [104]:
# 결측치를 포함한 열 삭제
df3 = df.dropna(axis=1)
df3

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [105]:
# 모든 값이 결측치인 행 삭제
df4 = df.dropna(how='all')
df4

age  gender  month_birth    hobby  target
0  42.0    male         12.0  reading  class2
1  35.0     NaN          3.0  cooking  class1
2   NaN  female          7.0  cycling  class3

In [106]:
# 값이 2개 미만인 행 삭제
df5 = df.dropna(thresh=2)
df5

age  gender  month_birth    hobby  target
0  42.0    male         12.0  reading  class2
1  35.0     NaN          3.0  cooking  class1
2   NaN  female          7.0  cycling  class3

In [107]:
# 특정 열에 결측치가 있는 경우
df6 = df.dropna(subset=['gender'])
df6

age  gender  month_birth    hobby  target
0  42.0    male         12.0  reading  class2
2   NaN  female          7.0  cycling  class3

In [153]:
# 결측치 대체하기
alter_values = {'age': 0, 'gender': 'U', 'month_birth': 0, 'target': 'class4'}
df7=df.fillna(value=alter_values)
df7

age  gender  month_birth    hobby  target
0  42.0    male         12.0  reading  class2
1  35.0       U          3.0  cooking  class1
2   0.0  female          7.0  cycling  class3
3   0.0       U          0.0      NaN  class4

### 클래스 라벨 설정하기 
문자열을 정수로 변환

In [154]:
# 사이킷런의 preprocessing 패키지의 LabelEncoder 함수를 사용
from sklearn.preprocessing import LabelEncoder
df8 = df7
class_label = LabelEncoder()
data_value = df8['target'].values
y_new = class_label.fit_transform(data_value)
y_new

array([1, 0, 2, 3])

In [155]:
df8['target'] = y_new
df8

age  gender  month_birth    hobby  target
0  42.0    male         12.0  reading       1
1  35.0       U          3.0  cooking       0
2   0.0  female          7.0  cycling       2
3   0.0       U          0.0      NaN       3

In [156]:
# 클래스 라벨링 이후 다시 돌리려면
y_ori = class_label.inverse_transform(y_new)
y_ori

array(['class2', 'class1', 'class3', 'class4'], dtype=object)

In [157]:
df8['target'] = y_ori
df8

age  gender  month_birth    hobby  target
0  42.0    male         12.0  reading  class2
1  35.0       U          3.0  cooking  class1
2   0.0  female          7.0  cycling  class3
3   0.0       U          0.0      NaN  class4

In [158]:
# 사이킷런 라이브러리 사용하지 않고 클래스 라벨링
y_arr = df8['target'].values
unique_y = pd.unique(y_arr)
unique_y.sort()
dic_y = {value: idx for idx, value in enumerate(unique_y)}
print(dic_y)

df8['target'] = df8['target'].map(dic_y)
df8

{'class1': 0, 'class2': 1, 'class3': 2, 'class4': 3}


age  gender  month_birth    hobby  target
0  42.0    male         12.0  reading       1
1  35.0       U          3.0  cooking       0
2   0.0  female          7.0  cycling       2
3   0.0       U          0.0      NaN       3

### 원-핫 인코딩(더미 변수)
오직 0과 1만 사용한 벡터를 이용해 데이터 값을 나타내는 것

In [159]:
df9 = df8

# 타깃 데이터값을 문자열로 변환
df9['target'] = df9['target'].astype(str)

df10 = pd.get_dummies(df9['target'])
print(df10)

       0      1      2      3
0  False   True  False  False
1   True  False  False  False
2  False  False   True  False
3  False  False  False   True


In [160]:
# 길이가 4인 벡터에서 길이가 3인 벡터로 표현
df9['target'] = df9['target'].astype(str)
df11 = pd.get_dummies(df9['target'], drop_first=True)
print(df11)

       1      2      3
0   True  False  False
1  False  False  False
2  False   True  False
3  False  False   True


In [161]:
df12 = df8
df13 = pd.get_dummies(df12)
df13

age  month_birth  gender_U  gender_female  gender_male  hobby_cooking  \
0  42.0         12.0     False          False         True          False   
1  35.0          3.0      True          False        False           True   
2   0.0          7.0     False           True        False          False   
3   0.0          0.0      True          False        False          False   

   hobby_cycling  hobby_reading  target_0  target_1  target_2  target_3  
0          False           True     False      True     False     False  
1          False          False      True     False     False     False  
2           True          False     False     False      True     False  
3          False          False     False     False     False      True

In [162]:
# '태어난 달' 열의 데이터값을 사이킷런 라이브러리의 원-핫 인코딩
from sklearn.preprocessing import OneHotEncoder
hot_encoder = OneHotEncoder()
y = df7[['month_birth']]
print(y)
y_hot = hot_encoder.fit_transform(y)
print(y_hot.toarray())

   month_birth
0         12.0
1          3.0
2          7.0
3          0.0
[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]


### 데이터 스케일링이란?
**데이터 값이 단위에 영향을 받지 않도록 변형하는 것**
**1. 표준화 스케일링 :  데이터가 평균 0, 표준 편차 1이 되도록 편경하는 방법**
**2. 로버스트 스케일링 : 표준화 스케일을 변형한 방법으로 중앙값과 사분위수를 사용 -> 극단 값의 영향을 거의 받지 않는다.** 
**3. 최소-최대 스케일링(min-max scaling) : 데이터값의 최댓값이 1, 최솟값 0으로 데이터값이 가질 수 있는 범위를 제한**
**4. 노멀 스케일링 : 벡터의 유클리디안 길이가 1이 되도록 데이터값을 변경, 방향(각도)만 고려 / 행 기준으로 스케일링**

**추가사항**
트레인 데이터 : fit_transform
테스트 데이터 : transform
 -> 트레이닝 데이터 스케일링에 사용했던 평균, 표준 편차등을 테스트 데이터에도 동일하게 사용하겠다는 의미

In [163]:
# 표준화 스케일링
from sklearn.preprocessing import StandardScaler

std = StandardScaler()
x_std = std.fit_transform(df8[['month_birth']])
x_std

array([[ 1.44444444],
       [-0.55555556],
       [ 0.33333333],
       [-1.22222222]])

In [167]:
print(np.mean(x_std))
print(np.std(x_std))

-5.551115123125783e-17
1.0


In [168]:
#로버스트 스케일링
from sklearn.preprocessing import RobustScaler

robust = RobustScaler()
robust.fit(df8[['month_birth']])
x_robust = robust.transform(df8[['month_birth']])
x_robust

array([[ 1.16666667],
       [-0.33333333],
       [ 0.33333333],
       [-0.83333333]])

In [169]:
#최소-최대 스케일링
from sklearn.preprocessing import MinMaxScaler

minmax = MinMaxScaler()
minmax.fit(df8[['month_birth']])
x_minmax = minmax.transform(df8[['month_birth']])
x_minmax

array([[1.        ],
       [0.25      ],
       [0.58333333],
       [0.        ]])

In [170]:
# 노멀 스케일링
from sklearn.preprocessing import Normalizer

normal = Normalizer()
normal.fit(df8[['age', 'month_birth']])
x_normal = normal.transform(df8[['age', 'month_birth']])
x_normal

array([[0.96152395, 0.27472113],
       [0.99634665, 0.08540114],
       [0.        , 1.        ],
       [0.        , 0.        ]])